const b=(text:string,data:string)=>({text,callback_data:data});
export const mainMenu={inline_keyboard:[[b("📝 Пост","menu:post"),b("🎬 Сценарий","menu:script")],[b("♻️ Переработка","menu:repurpose"),b("📅 План","menu:plan")],[b("👤 Мой стиль","menu:style"),b("🕘 История","menu:history")],[b("💎 Тарифы","menu:pricing"),b("⭐ Credits","menu:credits")],[b("⚙️ Настройки","menu:settings")]]};
export const persistentMenu={keyboard:[[{text:"📝 Пост"},{text:"🎬 Сценарий"}],[{text:"♻️ Переработка"},{text:"📅 План"}],[{text:"👤 Мой стиль"},{text:"🕘 История"}],[{text:"💎 Тарифы"},{text:"⭐ Credits"}],[{text:"⚙️ Настройки"}]],resize_keyboard:true,is_persistent:true};
export type PostDraft={topic:string;platform:string;style:string;length:string};
export type ScriptDraft={topic:string;platform:string;style:string;duration:string};
export type PlanDraft={topic:string;goal:string;platform:string;style:string};
export const postConfig=(d:PostDraft)=>({inline_keyboard:[[b(d.platform==="telegram"?"✅ Telegram":"Telegram","post:p:telegram"),b(d.platform==="instagram"?"✅ Instagram":"Instagram","post:p:instagram")],[b(d.platform==="tiktok"?"✅ TikTok":"TikTok","post:p:tiktok"),b(d.platform==="youtube"?"✅ YouTube":"YouTube","post:p:youtube")],[b(d.style==="expert"?"✅ Экспертный":"Экспертный","post:s:expert"),b(d.style==="provocative"?"✅ Провокационный":"Провокационный","post:s:provocative")],[b(d.style==="conversational"?"✅ Разговорный":"Разговорный","post:s:conversational"),b(d.style==="news"?"✅ Новостной":"Новостной","post:s:news")],[b(d.style==="sales"?"✅ Продающий":"Продающий","post:s:sales")],[b(d.length==="short"?"✅ Короткая":"Короткая","post:l:short"),b(d.length==="medium"?"✅ Средняя":"Средняя","post:l:medium"),b(d.length==="long"?"✅ Длинная":"Длинная","post:l:long")],[b("🚀 Создать","post:create")],[b("← Назад","post:back")]]});
export const scriptConfig=(d:ScriptDraft)=>({inline_keyboard:[[b(d.platform==="tiktok"?"✅ TikTok":"TikTok","script:p:tiktok"),b(d.platform==="instagram"?"✅ Instagram":"Instagram","script:p:instagram")],[b(d.platform==="youtube"?"✅ YouTube Shorts":"YouTube Shorts","script:p:youtube")],[b(d.style==="dynamic"?"✅ Динамичный":"Динамичный","script:s:dynamic"),b(d.style==="expert"?"✅ Экспертный":"Экспертный","script:s:expert")],[b(d.style==="conversational"?"✅ Разговорный":"Разговорный","script:s:conversational"),b(d.style==="sales"?"✅ Продающий":"Продающий","script:s:sales")],[b(d.duration==="30"?"✅ 30 сек":"30 сек","script:d:30"),b(d.duration==="45"?"✅ 45 сек":"45 сек","script:d:45"),b(d.duration==="60"?"✅ 60 сек":"60 сек","script:d:60")],[b("🚀 Создать","script:create")],[b("← Назад","script:back")]]});
export const planConfig=(d:PlanDraft)=>({inline_keyboard:[[b(d.goal==="growth"?"✅ Рост":"Рост","plan:g:growth"),b(d.goal==="sales"?"✅ Продажи":"Продажи","plan:g:sales")],[b(d.goal==="engagement"?"✅ Вовлечение":"Вовлечение","plan:g:engagement"),b(d.goal==="expertise"?"✅ Экспертность":"Экспертность","plan:g:expertise")],[b(d.platform==="telegram"?"✅ Telegram":"Telegram","plan:p:telegram"),b(d.platform==="instagram"?"✅ Instagram":"Instagram","plan:p:instagram")],[b(d.platform==="tiktok"?"✅ TikTok":"TikTok","plan:p:tiktok"),b(d.platform==="youtube"?"✅ YouTube":"YouTube","plan:p:youtube")],[b(d.style==="expert"?"✅ Экспертный":"Экспертный","plan:s:expert"),b(d.style==="conversational"?"✅ Разговорный":"Разговорный","plan:s:conversational")],[b(d.style==="dynamic"?"✅ Динамичный":"Динамичный","plan:s:dynamic"),b(d.style==="sales"?"✅ Продающий":"Продающий","plan:s:sales")],[b("🚀 Создать","plan:create")],[b("← Назад","plan:back")]]});
export const repurposeTargets=(selected:string[])=>({inline_keyboard:[[b(selected.includes("all")?"✅ Всё сразу":"🚀 Всё сразу","rep:target:all")],[b(selected.includes("telegram")?"✅ Telegram":"📱 Telegram","rep:target:telegram"),b(selected.includes("instagram")?"✅ Instagram":"📸 Instagram","rep:target:instagram")],[b(selected.includes("tiktok")?"✅ TikTok":"🎵 TikTok","rep:target:tiktok"),b(selected.includes("youtube")?"✅ YouTube":"▶️ YouTube","rep:target:youtube")],[b(selected.includes("hooks")?"✅ 5 Hooks":"🔥 5 Hooks","rep:target:hooks"),b(selected.includes("cta")?"✅ CTA":"🎯 CTA","rep:target:cta")],[b(selected.includes("plan")?"✅ План на неделю":"📅 Контент на неделю","rep:target:plan")],[b("🚀 Создать","rep:create")],[b("← Назад","rep:back")]]});
export const postResult=(jobId:number,copyText="")=>({inline_keyboard:[[b("🔄 Ещё вариант",`post:regen:${jobId}`),b("🔥 Усилить Hook",`post:hook:${jobId}`),b("✂️ Сократить",`post:shorten:${jobId}` )],[b("🎬 Сделать сценарий",`post:script:${jobId}`),{text:"📋 Копировать",copy_text:{text:copyText.slice(0,256)}}],[b("← Назад",`post:back-result:${jobId}`)]]});
export const pricingKeyboard={inline_keyboard:[[b("⭐ Creator — 99 ⭐","buy:creator")],[b("🔥 Pro — 299 ⭐","buy:pro")],[b("⭐ Купить credits","buy:credits")],[b("← Назад","menu:back")]]};

export const scriptResult=(jobId:number)=>({inline_keyboard:[[b("← Назад",`script:back-result:${jobId}`)]]});
export const planResult=(jobId:number,days:any[]=[])=>({inline_keyboard:[...days.slice(0,7).map((d:any,i:number)=>[b(`${d.day} · ${String(d.title).slice(0,28)}`,`plan:view:${jobId}:${i}`)]),[b("← Назад",`plan:back-result:${jobId}`)]]});
