import {and,desc,eq} from "drizzle-orm";
import {createDb} from "../db/client";
import {creditLedger,jobs,payments,projects,userSessions,users,subscriptions} from "../db/schema";
import {ensureUser,reserveCredits,refundCredits} from "../billing/credits";
import {getPrice,getPackage} from "../config";
import {answerCallback,answerPreCheckoutQuery,deleteMessage,editMessageText,sendInvoice,sendMessage} from "./api";
import {mainMenu,persistentMenu,postConfig,postResult,pricingKeyboard,creditsKeyboard,repurposeConfirm,repurposeResult,repurposeTargets,scriptConfig,scriptResult,planConfig,planResult,settingsKeyboard,languageKeyboard,notificationKeyboard,errorKeyboard} from "./keyboards";
import type {Bindings} from "../env";

type Flow="post"|"script"|"plan"|"repurpose";
const defaults={post:{topic:"",platform:"telegram",style:"conversational",length:"short"},script:{topic:"",platform:"tiktok",style:"dynamic",duration:"30"},plan:{topic:"",goal:"growth",platform:"telegram",style:"expert"},repurpose:{material:"",targets:["all"] as string[]}};
const menuText=(name:string)=>"🤖 Привет, "+name+"!\n\nТы в Creator AI — пространстве, где одна идея превращается в полноценный\nконтент.\n\nТебе достаточно написать, что ты хочешь рассказать, или отправить уже\nготовый материал.\n\nДальше Creator AI может:\n\n✦ превратить идею в сильный пост ✦ создать сценарий для короткого ролика\n✦ переработать статью, текст, аудио или видео в разные форматы ✦\nсоставить контент-план на 7 дней ✦ адаптировать контент под разные\nплощадки ✦ со временем научиться писать в твоей манере\n\n⚡ Меньше времени на создание. Больше готового контента.\n\nВсё управление — прямо здесь, в Telegram.\n\nЧто создаём сегодня, "+name+"? 👇";
const entry={post:"✦ Creator AI / Post Maker\n\nПревратим твою мысль в контент, который хочется дочитать.\n\nНапиши тему, идею или просто набросок того, что хочешь сказать.\n\nЯ помогу: — найти сильный Hook — выстроить структуру — раскрыть главную мысль — адаптировать под нужную площадку\n\n💡 Пример: «5 способов использовать AI в Telegram»\n\nНачни с одной идеи. Остальное сделаем вместе.",script:"✦ Creator AI / Script Maker\n\nПревратим твою идею в ролик, который хочется досмотреть.\n\nНапиши тему, идею или просто расскажи, что хочешь донести зрителю.\n\nЯ помогу: — создать сильный Hook с первых секунд — выстроить сценарий и динамику ролика — написать текст для диктора — подобрать идеи для визуала — добавить текст на экран и CTA\n\n💡 Пример: «5 AI-инструментов, которые можно использовать прямо с телефона»\n\nНачни с одной идеи. Сценарий соберём вместе.",repurpose:"✦ Creator AI / Repurpose\n\nПревратим твой готовый материал в контент для разных площадок.\n\nОтправь статью, пост, текст, расшифровку аудио или видео — или просто вставь материал сюда.\n\nЯ помогу: — выделить главные мысли — превратить материал в сильный Telegram-пост — адаптировать его для Instagram и других площадок — создать сценарий для короткого ролика — придумать несколько сильных Hook — добавить CTA под каждый формат\n\n💡 Пример: «Вот моя статья о том, как использовать AI для работы. Сделай из неё пост, сценарий для Reels и 5 Hook.»\n\nОдин материал. Несколько форматов. Больше контента.",plan:"✦ Creator AI / Content Plan\n\nСоздадим контент-план на 7 дней, чтобы тебе не приходилось каждый день думать, что публиковать.\n\nНапиши свою тему, нишу или цель — например, что хочешь продвигать или о чём рассказывать.\n\nЯ помогу: — придумать идеи на каждый день — распределить контент по форматам — добавить сильный Hook к каждой публикации — определить основную мысль и CTA — сохранить баланс между пользой, вовлечением и продвижением\n\n💡 Пример: «Моя тема — AI и Telegram. Хочу вести канал и привлекать новых подписчиков.»\n\n7 дней. 7 идей. Один понятный план действий."};
const uiState=(kind:string,messageId:number,extra:any={})=>({kind,messageId,...extra});

export async function handleWebhook(env:Bindings,update:unknown){
 const u=update as any;
 if(u.pre_checkout_query){const q=u.pre_checkout_query;const db=createDb(env);const p=await db.select().from(payments).where(eq(payments.invoicePayload,String(q.invoice_payload))).get();const payer=await db.select().from(users).where(eq(users.telegramId,String(q.from?.id??""))).get();const ok=!!p&&p.status==="pending"&&!!payer&&p.userId===payer.id&&String(q.currency)==="XTR"&&Number(q.total_amount)===Number(p.starsAmount);await answerPreCheckoutQuery(env,q.id,ok,ok?undefined:"Платёж больше недоступен или не совпадает с заказом.");return;}
 const message=u.message,cb=u.callback_query,from=message?.from??cb?.from;if(!from)return;const chatId=String(message?.chat?.id??cb?.message?.chat?.id);const user=await ensureUser(env,String(from.id),from.first_name,from.username);const db=createDb(env);
 if(message?.successful_payment){await completePayment(env,user.id,message.successful_payment);await openMain(env,user.id,chatId);return;}
 if(message?.text==="/start"){await openMain(env,user.id,chatId);return;}
 if(message?.text){const text=message.text.trim();const map:any={"📝 Пост":"menu:post","🎬 Сценарий":"menu:script","♻️ Переработка":"menu:repurpose","📅 Контент-план":"menu:plan","👤 Мой стиль":"menu:style","🕘 История":"menu:history","💎 Тарифы":"menu:pricing","⭐ Credits":"menu:credits","⚙️ Настройки":"menu:settings"};if(map[text]){await deleteMessage(env,chatId,message.message_id).catch(()=>{});await action(env,user.id,chatId,map[text],null);return;}
  const s=await db.select().from(userSessions).where(eq(userSessions.userId,user.id)).get();
  if(s&&s.flow==="style"){const d=JSON.parse(s.draftJson??"{}");const examples=Array.isArray(d.examples)?d.examples:[];if(examples.length<20){examples.push(text.slice(0,4000));await db.update(userSessions).set({step:"style_examples",draftJson:JSON.stringify({examples}),updatedAt:new Date()}).where(eq(userSessions.userId,user.id));const keyboard=examples.length>=5?{inline_keyboard:[[{text:"✨ Проанализировать стиль",callback_data:"style:analyze"}],[{text:"← Назад",callback_data:"menu:back"}]]}:{inline_keyboard:[[{text:"← Назад",callback_data:"menu:back"}]]};await sendMessage(env,chatId,"✦ Creator AI / My Style\n\n🔹 Получено: "+examples.length+" / 20\n\n"+(examples.length>=5?"Можешь отправить ещё примеры, чтобы Creator AI точнее понял твою манеру, или запустить анализ уже сейчас.":"После 5 примеров можно будет запустить анализ."),keyboard);}return;}
  if(s&&["topic","material","config"].includes(s.step)){const d=JSON.parse(s.draftJson??"{}");if(s.flow==="post")d.topic=text.slice(0,12000);else if(s.flow==="script")d.topic=text.slice(0,12000);else if(s.flow==="plan")d.topic=text.slice(0,12000);else if(s.flow==="repurpose")d.material=text.slice(0,4000);await saveSession(db,user.id,s.flow as Flow,d,Number(d.__uiMessageId??0));const mid=Number(d.__uiMessageId??0);if(mid){const screen=s.flow==="post"?renderPost(d):s.flow==="script"?renderScript(d):s.flow==="plan"?renderPlan(d):"♻️ Creator AI / Repurpose\n\nМатериал проанализирован. Теперь выбери, какой контент создать из него.\n\n🔹 Стоимость: динамическая";const markup=s.flow==="post"?postConfig(d):s.flow==="script"?scriptConfig(d):s.flow==="plan"?planConfig(d):repurposeTargets(d.targets);await editMessageText(env,chatId,mid,screen,markup).catch(()=>{});}await deleteMessage(env,chatId,message.message_id).catch(()=>{});return;}}
 }
 if(!cb)return;await answerCallback(env,cb.id);await action(env,user.id,chatId,String(cb.data??""),cb.message);
}

async function action(env:Bindings,userId:number,chatId:string,data:string,msg:any){
 const db=createDb(env);
 const active=await db.select({id:jobs.id}).from(jobs).where(and(eq(jobs.userId,userId),eq(jobs.status,"processing"))).get();
 if(active&&!["menu:pricing","menu:credits","menu:settings","settings:profile","settings:language","settings:notifications","settings:support","settings:terms","settings:privacy"].includes(data)&&!data.startsWith("menu:")){const state=await db.select().from(userSessions).where(eq(userSessions.userId,userId)).get();const mid=state?Number(JSON.parse(state.draftJson??"{}").messageId??0):0;if(mid)await editMessageText(env,chatId,mid,"⏳ Генерация ещё выполняется…").catch(()=>{});return;}
 if(data==="menu:back"){return openMain(env,userId,chatId);}
 if(data==="menu:post")return openFeature(env,db,userId,chatId,"post");
 if(data==="menu:script")return openFeature(env,db,userId,chatId,"script");
 if(data==="menu:plan")return openFeature(env,db,userId,chatId,"plan");
 if(data==="menu:repurpose")return openFeature(env,db,userId,chatId,"repurpose");
 if(data.startsWith("buy:"))return buy(env,db,userId,chatId,data);\n if(data==="menu:style")return openStyle(env,db,userId,chatId);
 if(data==="menu:history")return history(env,db,userId,chatId,msg);
 if(data==="menu:pricing")return screen(env,db,userId,chatId,msg,"💎 CREATOR AI / ТАРИФЫ\n\nВыбирай уровень, который подходит твоему темпу создания контента.\n\n✨ FREE\n10 кредитов в месяц\n🕘 История — по сроку, заданному тарифной конфигурацией\n\n⚡ CREATOR\n99 ⭐ / месяц\n100 кредитов\n\n🚀 PRO\n299 ⭐ / месяц\n500 кредитов\n\nБольше контента. Меньше ограничений.",pricingKeyboard);
 if(data==="menu:credits"){const u=await db.select().from(users).where(eq(users.id,userId)).get();return screen(env,db,userId,chatId,msg,"💎 CREATOR AI / КРЕДИТЫ\n\nТвой текущий баланс:\n\n🔹 "+(u?.creditsBalance??0)+" кредитов\n\nНе хочешь менять тариф? Просто пополни баланс и продолжай создавать контент.\n\n✨ Выбери пакет кредитов:",creditsKeyboard());}
 if(data==="menu:settings")return screen(env,db,userId,chatId,msg,"⚙️ Creator AI / Настройки\n\nЗдесь можно изменить основные параметры Creator AI.\n\n👤 Аккаунт 🌐 Язык 🔔 Уведомления 💬 Помощь ⚖️ Условия использования 🛡️ Конфиденциальность",settingsKeyboard);
 if(data==="settings:language")return screen(env,db,userId,chatId,msg,"🌐 CREATOR AI / ЯЗЫК\n\nВыбери язык интерфейса и общения с Creator AI.\n\n🇷🇺 Русский 🇬🇧 English",languageKeyboard);
 if(data.startsWith("settings:language:")){await db.update(users).set({language:data.split(":")[2],updatedAt:new Date()}).where(eq(users.id,userId));return action(env,userId,chatId,"menu:settings",msg);}
 if(data==="settings:notifications"){const u=await db.select().from(users).where(eq(users.id,userId)).get();return screen(env,db,userId,chatId,msg,"🔔 CREATOR AI / УВЕДОМЛЕНИЯ\n\nБудь в курсе новых возможностей Creator AI.\n\n📢 Новости и обновления\nПолучать сообщения о новых функциях, важных изменениях и событиях Creator AI.\n\n"+(u?.notificationsEnabled?"🔔 Уведомления включены":"🔕 Уведомления выключены"),notificationKeyboard(!!u?.notificationsEnabled));}
 if(data==="settings:toggle-notifications"){const u=await db.select().from(users).where(eq(users.id,userId)).get();await db.update(users).set({notificationsEnabled:!u?.notificationsEnabled,updatedAt:new Date()}).where(eq(users.id,userId));return action(env,userId,chatId,"settings:notifications",msg);}
 if(data==="settings:profile"){const u=await db.select().from(users).where(eq(users.id,userId)).get();return screen(env,db,userId,chatId,msg,"👤 CREATOR AI / АККАУНТ\n\nТвоя информация в Creator AI.\n\n👤 "+(u?.firstName??"")+"\nID: "+(u?.telegramId??"")+"\n\n🔹 "+(u?.creditsBalance??0)+" кредитов\n💎 "+(u?.plan?.toUpperCase()??"FREE"),settingsKeyboard);}
 if(data==="settings:support")return screen(env,db,userId,chatId,msg,"💬 Помощь\n\nВозник вопрос или нужна помощь?\n\nНаша поддержка поможет разобраться с Creator AI и ответит на твои вопросы.\n\n💬 Связаться с поддержкой",settingsKeyboard);
 if(data==="settings:terms")return screen(env,db,userId,chatId,msg,"⚖️ Условия использования\n\nИспользование Creator AI регулируется опубликованными условиями сервиса.",settingsKeyboard);
 if(data==="settings:privacy")return screen(env,db,userId,chatId,msg,"🛡️ Конфиденциальность\n\nДанные обрабатываются в соответствии с политикой конфиденциальности сервиса.",settingsKeyboard);
 if(data==="style:analyze")return startStyleAnalysis(env,db,userId,chatId,msg);
 if(data.startsWith("post:p:")||data.startsWith("post:s:")||data.startsWith("post:l:"))return selectField(env,db,userId,chatId,data,"post",msg);
 if(data.startsWith("script:p:")||data.startsWith("script:s:")||data.startsWith("script:d:"))return selectField(env,db,userId,chatId,data,"script",msg);
 if(data.startsWith("plan:g:")||data.startsWith("plan:p:")||data.startsWith("plan:s:"))return selectField(env,db,userId,chatId,data,"plan",msg);
 if(data.startsWith("rep:target:"))return selectRepurpose(env,db,userId,chatId,data,msg);
 if(data==="post:create")return createFromSession(env,db,userId,chatId,"post",msg);
 if(data==="script:create")return createFromSession(env,db,userId,chatId,"script",msg);
 if(data==="plan:create")return createFromSession(env,db,userId,chatId,"plan",msg);
 if(data==="rep:create")return screen(env,db,userId,chatId,msg,"♻️ Creator AI / Repurpose\n\nМатериал проанализирован. Теперь выбери, какой контент создать из него.\n\n🔹 Стоимость: "+await repurposeCost(env,JSON.parse((await db.select().from(userSessions).where(eq(userSessions.userId,userId)).get())?.draftJson??"{}")),repurposeConfirm());
 if(data==="rep:confirm-create")return createFromSession(env,db,userId,chatId,"repurpose",msg);
 if(data.startsWith("save:")){await db.update(jobs).set({isSaved:true}).where(and(eq(jobs.id,Number(data.split(":")[1])),eq(jobs.userId,userId)));return sendMessage(env,chatId,"⭐ Сохранено в историю.",mainMenu);}
 if(data.startsWith("retry:"))return retryJob(env,db,userId,chatId,Number(data.split(":")[1]));
 if(data.startsWith("error:cancel:"))return openMain(env,userId,chatId);
 if(data.startsWith("post:variant:"))return variant(env,db,userId,chatId,Number(data.split(":")[2]),"post");
 if(data.startsWith("script:variant:"))return variant(env,db,userId,chatId,Number(data.split(":")[2]),"script");
 if(data.startsWith("plan:variant:"))return variant(env,db,userId,chatId,Number(data.split(":")[2]),"plan");
 if(data.startsWith("post:edit:"))return editJob(env,db,userId,chatId,Number(data.split(":")[2]),"post");
 if(data.startsWith("script:edit:"))return editJob(env,db,userId,chatId,Number(data.split(":")[2]),"script");
 if(data.startsWith("rep:variant:"))return variant(env,db,userId,chatId,Number(data.split(":")[2]),"repurpose");
 if(data.startsWith("history:view:"))return viewHistory(env,db,userId,chatId,msg,Number(data.split(":")[2]));
 if(data.startsWith("rep:view:"))return viewRep(env,db,userId,chatId,Number(data.split(":")[2]),data.split(":")[3]);
 if(data.startsWith("post:back-result:")||data.startsWith("script:back-result:")||data.startsWith("plan:back-result:")||data.startsWith("rep:back-result:"))return openMain(env,userId,chatId);
}

async function openMain(env:Bindings,userId:number,chatId:string){const db=createDb(env);const u=await db.select().from(users).where(eq(users.id,userId)).get();const name=u?.firstName??"Creator";const state=await db.select().from(userSessions).where(eq(userSessions.userId,userId)).get();const mid=state?Number(JSON.parse(state.draftJson??"{}").messageId??0):0;if(mid&&state?.flow==="ui"){const m=await editMessageText(env,chatId,mid,menuText(name),mainMenu).catch(()=>null);if(m)await setUi(db,userId,"menu",m.message_id);return m;}const m=await sendMessage(env,chatId,menuText(name),mainMenu);await setUi(db,userId,"menu",m.message_id);await sendMessage(env,chatId,"\u2063",persistentMenu);return m;}
async function openFeature(env:Bindings,db:any,userId:number,chatId:string,flow:Flow){const d:any={...defaults[flow]};d.credits=await getPrice(env,flow==="plan"?"content_plan":flow);const m=await sendMessage(env,chatId,entry[flow],flow==="post"?postConfig(d):flow==="script"?scriptConfig(d):flow==="plan"?planConfig(d):repurposeTargets(d.targets));await saveSession(db,userId,flow,d,m.message_id);return m;}
async function openStyle(env:Bindings,db:any,userId:number,chatId:string){const m=await sendMessage(env,chatId,"✦ Creator AI / My Style\n\nНаучим Creator AI писать контент в твоей манере.\n\nОтправь свои посты или другие материалы, которые хорошо передают твой стиль.\n\n📚 Можно отправить от 5 до 20 примеров. Отправляй их по одному или несколько подряд.\n\n🔹 Получено: 0 / 20\n\nПосле 5 примеров можно будет запустить анализ.",{inline_keyboard:[[ {text:"← Назад",callback_data:"menu:back"} ]]});await db.insert(userSessions).values({userId,flow:"style",step:"style_examples",draftJson:JSON.stringify({examples:[]}),updatedAt:new Date()}).onConflictDoUpdate({target:userSessions.userId,set:{flow:"style",step:"style_examples",draftJson:JSON.stringify({examples:[]}),updatedAt:new Date()}});return m;}
async function startStyleAnalysis(env:Bindings,db:any,userId:number,chatId:string,msg:any){const s=await db.select().from(userSessions).where(eq(userSessions.userId,userId)).get();const examples=JSON.parse(s?.draftJson??"{}").examples??[];if(examples.length<5)return;const cost=await getPrice(env,"style_profile");const id=await createJob(env,db,userId,chatId,"style_profile",{examples},cost,msg);return id;}
async function selectField(env:Bindings,db:any,userId:number,chatId:string,data:string,flow:Flow,msg:any){const s=await db.select().from(userSessions).where(eq(userSessions.userId,userId)).get();if(!s)return;const d=JSON.parse(s.draftJson??"{}");const parts=data.split(":");if(flow==="post"){if(parts[1]==="p")d.platform=parts[2];if(parts[1]==="s")d.style=parts[2];if(parts[1]==="l")d.length=parts[2];}else if(flow==="script"){if(parts[1]==="p")d.platform=parts[2];if(parts[1]==="s")d.style=parts[2];if(parts[1]==="d")d.duration=parts[2];}else{if(parts[1]==="g")d.goal=parts[2];if(parts[1]==="p")d.platform=parts[2];if(parts[1]==="s")d.style=parts[2];}await saveSession(db,userId,flow,d,Number(d.__uiMessageId??msg?.message_id??0));const text=flow==="post"?renderPost(d):flow==="script"?renderScript(d):renderPlan(d);return editMessageText(env,chatId,Number(d.__uiMessageId??msg?.message_id),text,flow==="post"?postConfig(d):flow==="script"?scriptConfig(d):planConfig(d));}
async function selectRepurpose(env:Bindings,db:any,userId:number,chatId:string,data:string,msg:any){const s=await db.select().from(userSessions).where(eq(userSessions.userId,userId)).get();if(!s)return;const d=JSON.parse(s.draftJson??"{}");const t=data.slice(11);d.targets=t==="all"?["all"]:(d.targets??[]).filter((x:string)=>x!=="all").includes(t)?(d.targets??[]).filter((x:string)=>x!==t):(d.targets??[]).filter((x:string)=>x!=="all").concat(t);await saveSession(db,userId,"repurpose",d,Number(d.__uiMessageId??msg?.message_id??0));return editMessageText(env,chatId,Number(d.__uiMessageId??msg?.message_id), "♻️ Creator AI / Repurpose\n\nМатериал проанализирован. Теперь выбери, какой контент создать из него.\n\n🔹 Стоимость: динамическая",repurposeTargets(d.targets));}
async function createFromSession(env:Bindings,db:any,userId:number,chatId:string,flow:Flow,msg:any){const s=await db.select().from(userSessions).where(eq(userSessions.userId,userId)).get();if(!s)return;const d=JSON.parse(s.draftJson??"{}");const cost=flow==="repurpose"?await repurposeCost(env,d):await getPrice(env,flow==="plan"?"content_plan":flow);return createJob(env,db,userId,chatId,flow,strip(d),cost,msg);}
async function createJob(env:Bindings,db:any,userId:number,chatId:string,type:string,input:any,cost:number,msg:any){if(!input||(type==="repurpose"?!input.material:!input.topic)&&type!=="style_profile")return;const active=await db.select({id:jobs.id}).from(jobs).where(and(eq(jobs.userId,userId),eq(jobs.status,"processing"))).get();if(active){await sendMessage(env,chatId,"⏳ Генерация ещё выполняется…");return;}const sent=msg?.message_id?await editMessageText(env,chatId,msg.message_id,processing(type,input)).catch(()=>null):null;const working=sent??await sendMessage(env,chatId,processing(type,input));const row=await db.insert(jobs).values({userId,type,status:"queued",inputJson:JSON.stringify(input),creditsReserved:0,telegramChatId:chatId,telegramMessageId:working.message_id,createdAt:new Date()}).returning({id:jobs.id}).get();if(!(await reserveCredits(env,userId,cost,row.id))){await db.delete(jobs).where(eq(jobs.id,row.id));await editMessageText(env,chatId,working.message_id,"💳 Недостаточно credits.\n\nВыбери, что сделать дальше.",creditsKeyboard());return;}await db.update(jobs).set({creditsReserved:cost}).where(eq(jobs.id,row.id));await setUi(db,userId,"processing",working.message_id,{jobId:row.id});try{await env.AI_QUEUE.send({jobId:row.id});}catch(e){await refundCredits(env,userId,cost,row.id);await db.update(jobs).set({status:"failed",creditsReserved:0,errorMessage:e instanceof Error?e.message:"queue_error",completedAt:new Date()}).where(eq(jobs.id,row.id));await editMessageText(env,chatId,working.message_id,"❌ Не удалось запустить генерацию.\n\nCredits возвращены.",errorKeyboard(row.id));}}
async function retryJob(env:Bindings,db:any,userId:number,chatId:string,id:number){const job=await db.select().from(jobs).where(and(eq(jobs.id,id),eq(jobs.userId,userId))).get();if(!job||job.status!=="failed")return;const input=JSON.parse(job.inputJson??"{}");const cost=await getPrice(env,job.type==="content_plan"?"content_plan":job.type as any).catch(()=>1);return createJob(env,db,userId,chatId,job.type,input,cost,null);}
async function variant(env:Bindings,db:any,userId:number,chatId:string,id:number,type:string){const job=await db.select().from(jobs).where(and(eq(jobs.id,id),eq(jobs.userId,userId))).get();if(!job)return;const input=JSON.parse(job.inputJson??"{}");const key=type==="plan"?"plan_variant":type==="repurpose"?"repurpose_variant":type+"_variant";const cost=await getPrice(env,key as any);return createJob(env,db,userId,chatId,type==="plan"?"content_plan":type,input,cost,null);}
async function editJob(env:Bindings,db:any,userId:number,chatId:string,id:number,type:string){const job=await db.select().from(jobs).where(and(eq(jobs.id,id),eq(jobs.userId,userId))).get();if(!job)return;const d=JSON.parse(job.inputJson??"{}");d.__sourceJobId=id;const m=await sendMessage(env,chatId,type==="post"?renderPost(d):renderScript(d),type==="post"?postConfig(d):scriptConfig(d));await saveSession(db,userId,type,d,m.message_id);}
async function history(env:Bindings,db:any,userId:number,chatId:string,msg:any){const rows=await db.select().from(jobs).where(and(eq(jobs.userId,userId),eq(jobs.status,"completed"),eq(jobs.isSaved,true))).orderBy(desc(jobs.createdAt)).limit(20);const buttons=rows.map(j=>[{text:label(j),callback_data:"history:view:"+j.id}]);buttons.push([{text:"← Назад",callback_data:"menu:back"}]);return screen(env,db,userId,chatId,msg,rows.length?"✦ CREATOR AI / HISTORY\n\nТвоя личная библиотека важных материалов.":"✦ CREATOR AI / HISTORY\n\nПока ничего не сохранено.",{inline_keyboard:buttons});}
async function viewHistory(env:Bindings,db:any,userId:number,chatId:string,msg:any,id:number){const j=await db.select().from(jobs).where(and(eq(jobs.id,id),eq(jobs.userId,userId),eq(jobs.isSaved,true))).get();if(!j?.outputJson)return;const o=JSON.parse(j.outputJson);const text=j.type==="post"?formatPost(o):j.type==="script"?formatScript(o):j.type==="content_plan"?formatPlan(o):"♻️ Creator AI / Repurpose\n\nРезультат сохранён.";const markup=j.type==="post"?postResult(id,String(o.title)+"\n\n"+String(o.body)):j.type==="script"?scriptResult(id,formatScript(o)):j.type==="content_plan"?planResult(id,o.days??[]):repurposeResult(id);return screen(env,db,userId,chatId,msg,text,markup);}
async function viewRep(env:Bindings,db:any,userId:number,chatId:string,id:number,key:string){const j=await db.select().from(jobs).where(and(eq(jobs.id,id),eq(jobs.userId,userId))).get();if(!j?.outputJson)return;const o=JSON.parse(j.outputJson);let v=key==="hooks"?(o.hooks??[]).map((x:string,i:number)=>(i+1)+". "+x).join("\n"):key==="plan"?(o.plan??[]).map((x:any)=>x.day+" — "+x.title+" · "+x.format).join("\n"):o[key]??"";return sendMessage(env,chatId,"♻️ "+key+"\n\n"+String(v).slice(0,3900),{inline_keyboard:[[{text:"← Назад",callback_data:"history:view:"+id}]]});}
async function completePayment(env:Bindings,userId:number,p:any){const db=createDb(env);const row=await db.select().from(payments).where(eq(payments.invoicePayload,String(p.invoice_payload))).get();if(!row||row.status==="paid")return;await db.update(payments).set({status:"paid",telegramPaymentChargeId:p.telegram_payment_charge_id}).where(eq(payments.id,row.id));const parts=String(row.invoicePayload).split(":");const key=parts[2]+(parts[3]?"_"+parts[3]:"");if(key.startsWith("credits_")){const pkg=await getPackage(env,Number(key.slice(8)));const u=await db.select().from(users).where(eq(users.id,userId)).get();if(!u)return;const bal=u.creditsBalance+pkg.credits;await db.update(users).set({creditsBalance:bal,updatedAt:new Date()}).where(eq(users.id,userId));await db.insert(creditLedger).values({userId,delta:pkg.credits,balanceAfter:bal,reason:"stars_credits",paymentId:row.id,createdAt:new Date()});return;}const grants:any={creator:{plan:"creator",credits:100},pro:{plan:"pro",credits:500}};const g=grants[key];if(!g)return;const u=await db.select().from(users).where(eq(users.id,userId)).get();if(!u)return;const now=new Date(),expires=new Date(now.getTime()+30*86400000),bal=u.creditsBalance+g.credits;await db.update(users).set({plan:g.plan,creditsBalance:bal,creditsResetAt:expires,updatedAt:now}).where(eq(users.id,userId));await db.insert(creditLedger).values({userId,delta:g.credits,balanceAfter:bal,reason:"subscription_grant",paymentId:row.id,createdAt:now});await db.insert(subscriptions).values({userId,plan:g.plan,provider:"telegram_stars",starsAmount:row.starsAmount,status:"active",currentPeriodStart:now,expiresAt:expires,telegramPaymentChargeId:p.telegram_payment_charge_id,invoicePayload:row.invoicePayload,isRecurring:false,createdAt:now,updatedAt:now});}
async function screen(env:Bindings,db:any,userId:number,chatId:string,msg:any,text:string,markup:any){if(msg?.message_id){await editMessageText(env,chatId,msg.message_id,text,markup).catch(()=>null);await setUi(db,userId,"menu",msg.message_id);return;}const m=await sendMessage(env,chatId,text,markup);await setUi(db,userId,"menu",m.message_id);return m;}
async function setUi(db:any,userId:number,kind:string,messageId:number,extra:any={}){await db.insert(userSessions).values({userId,flow:"ui",step:kind,draftJson:JSON.stringify(uiState(kind,messageId,extra)),updatedAt:new Date()}).onConflictDoUpdate({target:userSessions.userId,set:{flow:"ui",step:kind,draftJson:JSON.stringify(uiState(kind,messageId,extra)),updatedAt:new Date()}});}
async function saveSession(db:any,userId:number,flow:Flow,d:any,messageId:number){d.__uiMessageId=messageId;await db.insert(userSessions).values({userId,flow,step:d.topic||d.material?"config":"topic",draftJson:JSON.stringify(d),updatedAt:new Date()}).onConflictDoUpdate({target:userSessions.userId,set:{flow,step:d.topic||d.material?"config":"topic",draftJson:JSON.stringify(d),updatedAt:new Date()}});}
const strip=(d:any)=>{const x={...d};delete x.__uiMessageId;delete x.__sourceJobId;return x;};
const renderPost=(d:any)=>"✦ Creator AI / Post Maker\n\nТвоя идея готова. Теперь настроим, как она будет выглядеть.\n\n🔹 Стоимость: "+(d.credits??"—")+"\n\n📱 Площадка\n\n🎨 Стиль\n\n📏 Размер";
const renderScript=(d:any)=>"🎬 Creator AI / Script Maker\n\nВыбери, каким будет твой ролик.\n\n🔹 Стоимость: "+(d.credits??"—")+"\n\n📱 Формат\n\n🎨 Стиль\n\n⏱️ Длительность";
const renderPlan=(d:any)=>"📅 Creator AI / Content Plan\n\nНастрой параметры контент-плана.\n\n🔹 Стоимость: "+(d.credits??"—")+"\n\n🎯 Цель\n\n📱 Площадка\n\n🎨 Стиль";
const processing=(type:string,input:any)=>type==="post"?"⏳ Создаю пост...":type==="script"?"⏳ Создаю сценарий...":type==="content_plan"?"⏳ Создаю контент-план...":type==="style_profile"?"⏳ Анализирую твой стиль...":"⏳ Перерабатываю материал...";
async function repurposeCost(env:Bindings,d:any){if((d.targets??["all"]).includes("all"))return await getPrice(env,"repurpose");let total=0;for(const t of d.targets??[]){const key=("repurpose_"+t) as any;total+=await getPrice(env,key);}return total;}
const formatPost=(o:any)=>("✦ CREATOR AI / POST MAKER\n\n🚀 Пост готов\n\n"+o.title+"\n\n"+o.body).slice(0,4000);
const formatScript=(o:any)=>("🎬 Creator AI / Script Maker\n\n🚀 Сценарий готов\n\n"+o.title+"\n\n🔥 Hook:\n"+o.hook+"\n\n⏱️ "+o.duration+"\n\n"+(o.scenes??[]).map((s:any)=>"[ "+s.time+" ]\n🗣 "+s.spoken+"\n🎥 "+s.visual+"\n📝 "+s.onScreen).join("\n\n")+"\n\n🎯 CTA:\n"+o.cta).slice(0,4000);
const formatPlan=(o:any)=>("📅 Creator AI / Content Plan\n\n🚀 План готов\n\n"+o.topic+"\n\n"+(o.days??[]).map((d:any)=>d.day+"\n📝 "+d.title+"\n"+d.platform+" · "+d.format+"\n🔥 "+d.hook+"\n💡 "+d.mainThought+"\n🎯 "+d.cta).join("\n\n")).slice(0,4000);
const label=(j:any)=>{const i=JSON.parse(j.inputJson??"{}");const icon=j.type==="post"?"📝":j.type==="script"?"🎬":j.type==="repurpose"?"♻️":"📅";return icon+" "+String(i.topic??i.material??"Результат").slice(0,45);};\nasync function buy(env:Bindings,db:any,userId:number,chatId:string,data:string){const key=data.slice(4);let stars=0,title="",credits=0;if(key==="creator"){stars=99;title="CREATOR";credits=100;}else if(key==="pro"){stars=299;title="PRO";credits=500;}else if(key.startsWith("credits:")){const pkg=await getPackage(env,Number(key.slice(8)));stars=pkg.stars;title=pkg.credits+" Credits";credits=pkg.credits;}else return;const payload="creatorai:"+userId+":"+key+":"+Date.now();await db.insert(payments).values({userId,provider:"telegram_stars",kind:key.startsWith("credits:")?"credits":"subscription",invoicePayload:payload,currency:"XTR",starsAmount:stars,status:"pending",createdAt:new Date()});await sendInvoice(env,chatId,title,credits+" credits",payload,stars);}\n