import type {AIProvider,PostInput,PostOutput,ScriptInput,ScriptOutput,RepurposeInput,RepurposeOutput,PlanInput,PlanOutput,StyleProfileInput,StyleProfileOutput} from "./provider";
const schemas={
post:{type:"object",properties:{title:{type:"string"},body:{type:"string"},hook:{type:"string"},platform:{type:"string"},style:{type:"string"},length:{type:"string"}},required:["title","body","hook","platform","style","length"],additionalProperties:false},
script:{type:"object",properties:{title:{type:"string"},hook:{type:"string"},duration:{type:"string"},scenes:{type:"array",items:{type:"object",properties:{time:{type:"string"},spoken:{type:"string"},visual:{type:"string"},onScreen:{type:"string"}},required:["time","spoken","visual","onScreen"],additionalProperties:false}},cta:{type:"string"},platform:{type:"string"},style:{type:"string"}},required:["title","hook","duration","scenes","cta","platform","style"],additionalProperties:false},
repurpose:{type:"object",properties:{telegram:{type:"string"},instagram:{type:"string"},tiktok:{type:"string"},youtube:{type:"string"},hooks:{type:"array",items:{type:"string"}},cta:{type:"string"},plan:{type:"array",items:{type:"object",properties:{day:{type:"string"},title:{type:"string"},format:{type:"string"}},required:["day","title","format"],additionalProperties:false}},},required:["telegram","instagram","tiktok","youtube","hooks","cta","plan"],additionalProperties:false},
plan:{type:"object",properties:{topic:{type:"string"},days:{type:"array",items:{type:"object",properties:{day:{type:"string"},title:{type:"string"},goal:{type:"string"},format:{type:"string"},hook:{type:"string"},angle:{type:"string"},mainThought:{type:"string"},cta:{type:"string"},status:{type:"string"}},required:["day","title","goal","format","hook","angle","mainThought","cta","status"],additionalProperties:false}}},required:["topic","days"],additionalProperties:false},
style:{type:"object",properties:{vocabulary:{type:"string"},structure:{type:"string"},rhythm:{type:"string"},emotion:{type:"string"},humor:{type:"string"},emojis:{type:"string"},hooks:{type:"string"},cta:{type:"string"},instruction:{type:"string"}},required:["vocabulary","structure","rhythm","emotion","humor","emojis","hooks","cta","instruction"],additionalProperties:false}
} as const;
export class OpenAIProvider implements AIProvider{
constructor(private readonly apiKey:string,private readonly model:string){}
private async structured<T>(name:string,schema:object,instructions:string,input:string){
 const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${this.apiKey}`},body:JSON.stringify({model:this.model,instructions,input:[{role:"user",content:input}],text:{format:{type:"json_schema",name,strict:true,schema}}})});
 if(!response.ok)throw new Error(`openai_http_${response.status}`);
 const data=await response.json() as {output_text?:string;usage?:{input_tokens?:number;output_tokens?:number}};
 if(!data.output_text)throw new Error("openai_empty_output");
 return {output:JSON.parse(data.output_text) as T,model:this.model,inputTokens:data.usage?.input_tokens,outputTokens:data.usage?.output_tokens};
}
createPost(input:PostInput){return this.structured<PostOutput>("creator_post",schemas.post,"You are Creator AI. Create publish-ready social content. Preserve requested language. Style Profile controls manner only; never change facts, topic, platform or parameters.",`Topic: ${input.topic}\nPlatform: ${input.platform}\nStyle: ${input.style}\nLength: ${input.length}\nStyle Profile: ${input.styleProfile ?? "none"}`);}
createScript(input:ScriptInput){return this.structured<ScriptOutput>("creator_script",schemas.script,"You are Creator AI. Create a concise publish-ready short-form video script. Preserve requested language.",`Topic: ${input.topic}\nPlatform: ${input.platform}\nStyle: ${input.style}\nDuration: ${input.duration}`);}
createRepurpose(input:RepurposeInput){return this.structured<RepurposeOutput>("creator_repurpose",schemas.repurpose,"You are Creator AI. Transform one source into independent platform outputs. Do not invent unsupported facts.",`Source:\n${input.material}\n\nTargets: ${input.targets.join(", ")}\nStyle Profile: ${input.styleProfile ?? "none"}`);}
createPlan(input:PlanInput){return this.structured<PlanOutput>("creator_plan",schemas.plan,"You are Creator AI. Create seven independent content ideas/tasks, not seven finished posts. Respect supported platform formats only.",`Topic: ${input.topic}\nGoal: ${input.goal}\nPlatform: ${input.platform}\nStyle: ${input.style}\nStyle Profile: ${input.styleProfile ?? "none"}`);}
createStyleProfile(input:StyleProfileInput){return this.structured<StyleProfileOutput>("creator_style_profile",schemas.style,"You are Creator AI. Analyze the supplied examples and produce a compact reusable author-style profile. Do not summarize the topics; describe how the author writes.",input.examples.map((x,i)=>`EXAMPLE ${i+1}:\n${x}`).join("\n\n"));}
}