import type{Bindings}from"../env";
import{generate}from"../ai/engine";
import{getSettingNumber}from"../ai/router";
import{getPrice}from"../config";
import{copyFor}from"../text";
import{editMessageText,sendMessage}from"../telegram/api";
import{chargeCredits,refundCredits}from"../billing/credits";
import{storeContentPlan}from"./plan-store";
import{repurposeFailureKeyboard,errorKeyboard,repurposeTargets,postResult,planResult}from"../telegram/keyboards";
const parse=(v:any)=>{try{return v?JSON.parse(String(v)):{};}catch{return{};}};
const styleApplies=(o:string)=>["post","repurpose_telegram","repurpose_instagram","content_plan","repurpose_plan"].includes(o);
async function profile(env:Bindings,userId:number){return(await env.DB.prepare("SELECT profile_json FROM style_profiles WHERE user_id=? AND is_active=1 ORDER BY updated_at DESC LIMIT 1").bind(userId).first<any>())?.profile_json;}
async function userLang(env:Bindings,userId:number){const u=await env.DB.prepare("SELECT language FROM users WHERE id=?").bind(userId).first<any>();return String(u?.language)==="en"?"en":"ru";}
async function attemptWriter(env:Bindings,jobId:number,x:any){const now=Date.now();await env.DB.prepare("INSERT OR IGNORE INTO job_attempts(job_id,attempt_no,status,provider,model,input_tokens,output_tokens,cost_usd_micros,duration_ms,prompt_version,error_code,error_message,started_at,completed_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(jobId,Number(x.attempt??1),x.errorCode?"failed":"success",x.provider??null,x.model??null,Number(x.inputTokens??0),Number(x.outputTokens??0),Number(x.costUsdMicros??0),Number(x.durationMs??0),x.promptVersion??null,x.errorCode??null,x.errorMessage??null,now-Number(x.durationMs??0),now,now).run();}
export async function runJob(env:Bindings,id:number,resultId?:number){if(resultId)return runRepurposeResult(env,id,resultId);const claim=await env.DB.prepare("UPDATE jobs SET status='processing',started_at=COALESCE(started_at,?),attempts=attempts+1 WHERE id=? AND status='queued'").bind(Date.now(),id).run();if(claim.meta.changes!==1)return;const job=await env.DB.prepare("SELECT * FROM jobs WHERE id=?").bind(id).first<any>();if(!job)return;try{const d=parse(job.input_json);if(job.type==="repurpose"&&d.phase==="analysis"||job.type==="source_analysis")return sourceAnalysis(env,job);if(job.type==="style_profile")return styleProfile(env,job,d);if(job.type==="repurpose")return initializeRepurpose(env,job,d);if(job.type==="repurpose_result")return standaloneResult(env,job,d);if(["post","script","content_plan"].includes(String(job.type)))return single(env,job,d,String(job.type));return failJob(env,job,"unsupported_job_type");}catch(e){return failJob(env,job,e instanceof Error?e.message:String(e));}}
async function single(env:Bindings,job:any,d:any,op:string){const ai=await generate<any>(env,op,{operation:op,userInput:String(d.topic??d.userInput??""),parameters:d,source:d.sourceText,analysis:d.analysis,styleProfile:styleApplies(op)?await profile(env,job.user_id):undefined,previousResult:d.previousResult?JSON.stringify(d.previousResult):undefined,language:await userLang(env,job.user_id)},await getSettingNumber(env,"job_max_attempts",3));await attemptWriter(env,job.id,ai);const now=Date.now(),charged=Number(job.credits_reserved??0);const up=await env.DB.prepare("UPDATE jobs SET output_json=?,provider=?,model=?,tokens_input=?,tokens_output=?,cost_usd_micros=?,prompt_version=?,credits_charged=?,credits_reserved=0,status='completed',completed_at=?,updated_at=? WHERE id=? AND status='processing'").bind(JSON.stringify(ai.output),ai.provider,ai.model,ai.inputTokens,ai.outputTokens,ai.costUsdMicros??0,ai.promptVersion,charged,now,now,job.id).run();if(up.meta.changes!==1)return;await chargeCredits(env,job.user_id,charged,job.id);if(op==="content_plan")await storeContentPlan(env,job,ai.output,job.source_id??null);const rr=await env.DB.prepare("INSERT INTO job_results(job_id,user_id,result_type,position,status,content_json,credits_charged,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(job.id,job.user_id,op,0,"completed",JSON.stringify(ai.output),charged,now,now).run();const rid=Number(rr.meta.last_row_id);if(d.contentPlanDayId)await env.DB.prepare("UPDATE content_plan_days SET status='✅',job_id=?,result_id=?,updated_at=? WHERE id=?").bind(job.id,rid,now,Number(d.contentPlanDayId)).run();await enqueueDelivery(env,rid,job.user_id,0,String(job.telegram_chat_id??""));return finishJob(env,job);}
async function standaloneResult(env:Bindings,job:any,d:any){const rt=String(d.resultType??"telegram").replace(/^repurpose_/,""),op=resultOp(rt);const ai=await generate<any>(env,op,{operation:op,userInput:String(d.sourceText??d.topic??""),parameters:d,analysis:d.analysis,styleProfile:styleApplies(op)?await profile(env,job.user_id):undefined,previousResult:d.previousResult?JSON.stringify(d.previousResult):undefined,language:await userLang(env,job.user_id)},await getSettingNumber(env,"job_max_attempts",3));await attemptWriter(env,job.id,ai);const now=Date.now(),charged=Number(job.credits_reserved??0);const up=await env.DB.prepare("UPDATE jobs SET output_json=?,provider=?,model=?,tokens_input=?,tokens_output=?,cost_usd_micros=?,prompt_version=?,credits_charged=?,credits_reserved=0,status='completed',completed_at=?,updated_at=? WHERE id=? AND status='processing'").bind(JSON.stringify(ai.output),ai.provider,ai.model,ai.inputTokens,ai.outputTokens,ai.costUsdMicros??0,ai.promptVersion,charged,now,now,job.id).run();if(up.meta.changes!==1)return;await chargeCredits(env,job.user_id,charged,job.id);const rr=await env.DB.prepare("INSERT INTO job_results(job_id,user_id,result_type,position,status,content_json,credits_charged,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(job.id,job.user_id,op,0,"completed",JSON.stringify(ai.output),charged,now,now).run();await enqueueDelivery(env,Number(rr.meta.last_row_id),job.user_id,0,String(job.telegram_chat_id??""));return finishJob(env,job);}
async function sourceAnalysis(env:Bindings,job:any){const src=await env.DB.prepare("SELECT extracted_text FROM sources WHERE id=? AND user_id=?").bind(job.source_id,job.user_id).first<any>();if(!src?.extracted_text)return failJob(env,job,"source_missing");const ai=await generate<any>(env,"source_analysis",{operation:"source_analysis",userInput:String(src.extracted_text),parameters:{sourceId:job.source_id},language:await userLang(env,job.user_id)},await getSettingNumber(env,"job_max_attempts",3));await attemptWriter(env,job.id,ai);const now=Date.now();await env.DB.prepare("UPDATE sources SET analysis_json=?,updated_at=? WHERE id=? AND user_id=?").bind(JSON.stringify(ai.output),now,job.source_id,job.user_id).run();await env.DB.prepare("UPDATE jobs SET output_json=?,provider=?,model=?,tokens_input=?,tokens_output=?,cost_usd_micros=?,prompt_version=?,status='awaiting_selection',completed_at=?,updated_at=? WHERE id=? AND status='processing'").bind(JSON.stringify(ai.output),ai.provider,ai.model,ai.inputTokens,ai.outputTokens,ai.costUsdMicros??0,ai.promptVersion,now,now,job.id).run();const s=await env.DB.prepare("SELECT working_message_id,working_chat_id FROM user_sessions WHERE user_id=?").bind(job.user_id).first<any>();if(s?.working_chat_id&&s?.working_message_id){const u=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(job.user_id).first<any>(),t=copyFor(String(u?.language)==="en"?"en":"ru");const body=(t as any).repSelect(0);await env.DB.prepare("UPDATE user_sessions SET flow='repurpose',step='select',draft_json=?,active_job_id=NULL,updated_at=? WHERE user_id=?").bind(JSON.stringify({jobId:job.id,sourceId:job.source_id,analysis:ai.output,selectedOutputs:[],phase:"selection"}),now,job.user_id).run();await editMessageText(env,String(s.working_chat_id),Number(s.working_message_id),body,repurposeTargets([],0)).catch(()=>{});}return;}
async function styleProfile(env:Bindings,job:any,d:any){
 const examples=Array.isArray(d.examples)?d.examples:[];
 if(examples.length<5)return failJob(env,job,"style_examples_insufficient");
 const ai=await generate<any>(env,"style_profile",{operation:"style_profile",userInput:examples.join("\n\n---EXAMPLE---\n\n"),parameters:{count:examples.length},language:await userLang(env,job.user_id)},await getSettingNumber(env,"job_max_attempts",3));
 await attemptWriter(env,job.id,ai);
 const now=Date.now();
 await env.DB.prepare("UPDATE style_profiles SET is_active=0,updated_at=? WHERE user_id=?").bind(now,job.user_id).run();
 const pr=await env.DB.prepare("INSERT INTO style_profiles(user_id,profile_json,is_active,created_at,updated_at) VALUES(?,?,?,?,?)").bind(job.user_id,JSON.stringify(ai.output),1,now,now).run();
 const pid=Number(pr.meta.last_row_id),charged=Number(job.credits_reserved??0);
 const up=await env.DB.prepare("UPDATE jobs SET output_json=?,style_profile_id=?,provider=?,model=?,tokens_input=?,tokens_output=?,cost_usd_micros=?,prompt_version=?,credits_charged=?,credits_reserved=0,status='completed',completed_at=?,updated_at=? WHERE id=? AND status='processing'").bind(JSON.stringify(ai.output),pid,ai.provider,ai.model,ai.inputTokens,ai.outputTokens,ai.costUsdMicros??0,ai.promptVersion,charged,now,now,job.id).run();
 if(up.meta.changes!==1)return;
 await chargeCredits(env,job.user_id,charged,job.id);
 const rr=await env.DB.prepare("INSERT INTO job_results(job_id,user_id,result_type,position,status,content_json,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?)").bind(job.id,job.user_id,"style_profile",0,"completed",JSON.stringify(ai.output),now,now).run();
 await enqueueDelivery(env,Number(rr.meta.last_row_id),job.user_id,0,String(job.telegram_chat_id??""));
 return finishJob(env,job);
}
async function initializeRepurpose(env:Bindings,job:any,d:any){const outs=Array.isArray(d.selectedOutputs)?d.selectedOutputs.map(String):[];if(!outs.length)return failJob(env,job,"no_outputs");const expected=await repurposeTotal(env,outs),n=await env.DB.prepare("UPDATE jobs SET credits_required=?,updated_at=? WHERE id=? AND status='processing'").bind(expected,Date.now(),job.id).run();if(n.meta.changes!==1)return;const rows=[];for(let i=0;i<outs.length;i++){const cost=await getPrice(env,"repurpose_"+outs[i]);rows.push(env.DB.prepare("INSERT OR IGNORE INTO job_results(job_id,user_id,result_type,position,status,credits_reserved,created_at) VALUES(?,?,?,?,?,?,?)").bind(job.id,job.user_id,outs[i],i,"queued",cost,Date.now()));}await Promise.all(rows);const q=await env.DB.prepare("SELECT id FROM job_results WHERE job_id=? AND status='queued' ORDER BY position").bind(job.id).all<any>();for(const x of q.results??[])await env.AI_QUEUE.send({jobId:job.id,resultId:Number(x.id)});}
async function runRepurposeResult(env:Bindings,jobId:number,resultId:number){const r=await env.DB.prepare("SELECT * FROM job_results WHERE id=? AND job_id=? AND status='queued'").bind(resultId,jobId).first<any>(),job=await env.DB.prepare("SELECT * FROM jobs WHERE id=?").bind(jobId).first<any>();if(!r||!job)return;const claim=await env.DB.prepare("UPDATE job_results SET status='processing' WHERE id=? AND status='queued'").bind(resultId).run();if(claim.meta.changes!==1)return;try{const src=await env.DB.prepare("SELECT * FROM sources WHERE id=? AND user_id=?").bind(job.source_id,job.user_id).first<any>();if(!src?.extracted_text)throw new Error("source_missing");const d=parse(job.input_json),op=resultOp(String(r.result_type));const ai=await generate<any>(env,op,{operation:op,userInput:String(src.extracted_text),parameters:{...d,resultType:r.result_type},analysis:String(src.analysis_json??"{}"),styleProfile:styleApplies(op)?await profile(env,job.user_id):undefined,language:await userLang(env,job.user_id)},await getSettingNumber(env,"job_max_attempts",3));await attemptWriter(env,job.id,ai);const now=Date.now(),reserved=Number(r.credits_reserved??0);await env.DB.prepare("UPDATE job_results SET status='completed',content_json=?,credits_charged=credits_reserved,credits_reserved=0,completed_at=? WHERE id=? AND status='processing'").bind(JSON.stringify(ai.output),now,r.id).run();await env.DB.prepare("UPDATE jobs SET credits_reserved=MAX(0,credits_reserved-?),credits_charged=credits_charged+?,updated_at=? WHERE id=?").bind(reserved,reserved,now,job.id).run();await chargeCredits(env,job.user_id,reserved,job.id);await enqueueDelivery(env,r.id,job.user_id,Number(r.position),String(job.telegram_chat_id??""));}catch(e){const reserved=Number(r.credits_reserved??0);await env.DB.prepare("UPDATE job_results SET status='failed',credits_reserved=0,error_code='AI_ERROR',error_message=?,completed_at=? WHERE id=? AND status='processing'").bind(String(e).slice(0,500),Date.now(),r.id).run();await env.DB.prepare("UPDATE jobs SET credits_reserved=MAX(0,credits_reserved-?),updated_at=? WHERE id=?").bind(reserved,Date.now(),job.id).run();if(reserved)await refundCredits(env,job.user_id,reserved,job.id,"result:"+r.id+":refund");}return maybeFinish(env,job);}
function resultOp(t:string){return t==="telegram"||t==="repurpose_telegram"?"repurpose_telegram":t==="instagram"||t==="repurpose_instagram"?"repurpose_instagram":t==="tiktok"||t==="repurpose_tiktok"?"repurpose_tiktok":t==="youtube"||t==="repurpose_youtube"?"repurpose_youtube":t==="hooks"||t==="repurpose_hooks"?"repurpose_hooks":t==="cta"||t==="repurpose_cta"?"repurpose_cta":"repurpose_plan";}
async function maybeFinish(env:Bindings,job:any){const q=await env.DB.prepare("SELECT status FROM job_results WHERE job_id=? ORDER BY position").bind(job.id).all<any>(),states=(q.results??[]).map((x:any)=>String(x.status));if(!states.length||states.some(x=>x==="queued"||x==="processing"))return;const good=states.filter(x=>x==="completed").length,bad=states.length-good;await env.DB.prepare("UPDATE jobs SET status=?,credits_reserved=0,completed_at=?,updated_at=? WHERE id=?").bind(good===0?"failed":bad?"partial":"completed",Date.now(),Date.now(),job.id).run();if(bad&&job.telegram_chat_id){const u=await env.DB.prepare("SELECT language FROM users WHERE id=?").bind(job.user_id).first<any>(),t=copyFor(String(u?.language)==="en"?"en":"ru");if(good===0)await sendMessage(env,job.telegram_chat_id,t.aiError).catch(()=>{});else await sendMessage(env,job.telegram_chat_id,"⚠️ "+(String(u?.language)==="en"?"Some results could not be created. Successful results remain available. Failed output costs were refunded.":"Часть результатов не удалось создать. Успешные результаты уже доступны. Стоимость неудачных результатов возвращена.")).catch(()=>{});}return finishJob(env,job);}
async function enqueueDelivery(env:Bindings,resultId:number,userId:number,position:number,chat:string){if(!chat)return;const q=await env.DB.prepare("INSERT OR IGNORE INTO deliveries(result_id,user_id,position,chat_id,status,created_at) VALUES(?,?,?,?,?,?)").bind(resultId,userId,position,chat,"queued",Date.now()).run();if(q.meta.changes===1)await env.DELIVERY_QUEUE.send({deliveryId:Number(q.meta.last_row_id)});}
async function finishJob(env:Bindings,job:any){await env.DB.prepare("UPDATE users SET generation_lock_job_id=NULL,updated_at=? WHERE id=? AND generation_lock_job_id=?").bind(Date.now(),job.user_id,job.id).run();await env.DB.prepare("UPDATE user_sessions SET active_job_id=NULL WHERE user_id=? AND active_job_id=?").bind(job.user_id,job.id).run();}
async function failJob(env:Bindings,job:any,reason:string){const reserved=Number(job.credits_reserved??0);if(reserved)await refundCredits(env,job.user_id,reserved,job.id,"job:"+job.id+":refund");const d=parse(job.input_json);if(d.contentPlanDayId)await env.DB.prepare("UPDATE content_plan_days SET status='❌',updated_at=? WHERE id=?").bind(Date.now(),Number(d.contentPlanDayId)).run();const t=copyFor(await userLang(env,job.user_id));await env.DB.prepare("UPDATE jobs SET status='failed',credits_reserved=0,error_code='AI_ERROR',error_message=?,completed_at=?,updated_at=? WHERE id=?").bind(reason.slice(0,500),Date.now(),Date.now(),job.id).run();await finishJob(env,job);if(job.telegram_chat_id&&job.telegram_message_id)await editMessageText(env,job.telegram_chat_id,Number(job.telegram_message_id),t.aiError,errorKeyboard(job.id)).catch(()=>{});}
async function repurposeTotal(env:Bindings,a:string[]){let n=0;for(const x of a)n+=await getPrice(env,"repurpose_"+x);return n;}
export function plainResult(t:string,o:any){
 if(t==="repurpose_hooks")return (o.hooks??[]).map((x:string,i:number)=>(i+1)+". "+x).join("\n");
 if(t==="repurpose_cta")return (o.ctas??[]).map((x:string,i:number)=>(i+1)+". "+x).join("\n");
 if(["script","repurpose_tiktok","repurpose_youtube"].includes(t))return [o.title?"🎬 "+o.title:"",o.hook?"🔥 Hook: "+o.hook:"",(o.scenes??[]).map((s:any)=>String(s.time)+"\n🎙 "+String(s.spoken)+"\n🎥 "+String(s.visual)+"\n🖥 "+String(s.onScreen)).join("\n\n"),o.cta?"🎯 CTA: "+o.cta:""].filter(Boolean).join("\n\n");
 if(["content_plan","repurpose_plan"].includes(t))return (o.days??[]).map((d:any)=>String(d.day)+" — "+String(d.title)+"\n"+String(d.goal)+"\n"+String(d.format)+"\n"+String(d.hook)+"\n"+String(d.angle)+"\n"+String(d.mainThought)+"\n"+String(d.cta)).join("\n\n");
 if(t==="style_profile")return "Профиль стиля сохранён.";
 return String(o.body??o.content??o.title??"").trim();
}
export function resultMarkup(t:string,o:any){
 if(t==="post"||t==="repurpose_telegram")return "✦ CREATOR AI / POST MAKER\n\n🚀 Пост готов\n\n"+String(o.title??"")+"\n\n"+String(o.body??o.content??"");
 if(t==="repurpose_instagram")return "✦ CREATOR AI / INSTAGRAM\n\n🚀 Caption готов\n\n"+String(o.body??o.content??"");
 if(["script","repurpose_tiktok","repurpose_youtube"].includes(t))return "🎬 CREATOR AI / SCRIPT MAKER\n\n🚀 Сценарий готов\n\n"+plainResult(t,o);
 if(t==="repurpose_hooks")return "✦ CREATOR AI / 5 HOOK\n\n🚀 Hook готовы\n\n"+plainResult(t,o);
 if(t==="repurpose_cta")return "✦ CREATOR AI / 3 CTA\n\n🚀 CTA готовы\n\n"+plainResult(t,o);
 if(t==="style_profile")return "✦ Creator AI / My Style\n\n✨ Стиль проанализирован\n\nПрофиль сохранён и будет использоваться в поддерживаемых текстовых генерациях.";
 return "📅 CREATOR AI / CONTENT PLAN\n\n🚀 Контент-план готов\n\n"+plainResult(t,o);
}